/* tslint:disable */
/* eslint-disable */
/**
 * FP Order service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonBet
 */
export interface PersonBet {
    /**
     * 
     * @type {string}
     * @memberof PersonBet
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof PersonBet
     */
    takeOffId?: number;
    /**
     * 
     * @type {string}
     * @memberof PersonBet
     */
    personMoney?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonBet
     */
    time?: string;
    /**
     * queue | ready | taken
     * @type {string}
     * @memberof PersonBet
     */
    status?: string;
}

export function PersonBetFromJSON(json: any): PersonBet {
    return PersonBetFromJSONTyped(json, false);
}

export function PersonBetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonBet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'takeOffId': !exists(json, 'takeOffId') ? undefined : json['takeOffId'],
        'personMoney': !exists(json, 'personMoney') ? undefined : json['personMoney'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function PersonBetToJSON(value?: PersonBet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'takeOffId': value.takeOffId,
        'personMoney': value.personMoney,
        'time': value.time,
        'status': value.status,
    };
}


