/* tslint:disable */
/* eslint-disable */
/**
 * FP Order service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonVideo
 */
export interface PersonVideo {
    /**
     * 
     * @type {string}
     * @memberof PersonVideo
     */
    time: string;
    /**
     * 
     * @type {string}
     * @memberof PersonVideo
     */
    name?: string;
}

export function PersonVideoFromJSON(json: any): PersonVideo {
    return PersonVideoFromJSONTyped(json, false);
}

export function PersonVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonVideo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'time': json['time'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PersonVideoToJSON(value?: PersonVideo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'time': value.time,
        'name': value.name,
    };
}


